"""
WasteWise AI - IBM Granite LLM Integration Module

Handles communication with IBM Granite models via watsonx.ai REST API / SDK.
Reads credentials strictly from environment variables. Includes a safe Mock Mode
when live credentials are not present in the environment.
"""

import os
import sys
import json
from pathlib import Path
from typing import Dict, Any, Optional

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.rag.prompt_builder import build_rag_prompt

# Default IBM Granite Configuration
DEFAULT_GRANITE_MODEL = os.getenv("GRANITE_MODEL_ID", "ibm/granite-3-8b-instruct")
DEFAULT_WATSONX_URL = os.getenv("WATSONX_URL", "https://us-south.ml.cloud.ibm.com")


class IBMGraniteClient:
    """
    Client for calling IBM Granite models on watsonx.ai.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        project_id: Optional[str] = None,
        url: Optional[str] = None,
        model_id: str = DEFAULT_GRANITE_MODEL,
        force_mock: bool = False
    ):
        self.api_key = api_key or os.getenv("WATSONX_APIKEY") or os.getenv("IBM_CLOUD_APIKEY")
        self.project_id = project_id or os.getenv("WATSONX_PROJECT_ID")
        self.url = url or DEFAULT_WATSONX_URL
        self.model_id = model_id
        self.force_mock = force_mock

        # Determine if we can run live calls or must use mock mode
        self.is_live = bool(self.api_key and self.project_id and not self.force_mock)
        self.watsonx_model = None

        if self.is_live:
            try:
                from ibm_watsonx_ai import Credentials
                from ibm_watsonx_ai.foundation_models import ModelInference

                credentials = Credentials(url=self.url, api_key=self.api_key)
                self.watsonx_model = ModelInference(
                    model_id=self.model_id,
                    credentials=credentials,
                    project_id=self.project_id
                )
            except Exception as err:
                print(f"[WARNING] Failed to initialize live watsonx.ai client: {err}")
                self.is_live = False

    def generate_response(self, prompt_package: Dict[str, Any]) -> Dict[str, Any]:
        """
        Processes a RAG prompt package generated by build_rag_prompt().

        Args:
            prompt_package: Output dictionary from src.rag.prompt_builder.build_rag_prompt()

        Returns:
            Dictionary containing AI response, status, and metadata.
        """
        # 1. Check Confidence Gate: Do NOT call Granite if confidence is low or category is unknown
        if not prompt_package.get("is_reliable", False):
            return {
                "status": prompt_package.get("status", "unreliable"),
                "is_reliable": False,
                "granite_called": False,
                "model_id": self.model_id,
                "is_live_service": False,
                "response_text": prompt_package.get("user_message"),
                "explanation": "Confidence gate triggered: Granite call skipped to prevent ungrounded advice."
            }

        prompt_text = prompt_package.get("llm_prompt")
        if not prompt_text:
            return {
                "status": "error",
                "is_reliable": False,
                "granite_called": False,
                "response_text": "Error: Empty prompt package provided.",
                "explanation": "No valid LLM prompt string found in package."
            }

        # 2. Live IBM WatsonX API Call
        if self.is_live and self.watsonx_model:
            try:
                params = {
                    "decoding_method": "greedy",
                    "max_new_tokens": 300,
                    "min_new_tokens": 20,
                    "temperature": 0.2,
                    "repetition_penalty": 1.1
                }
                generated_response = self.watsonx_model.generate_text(prompt=prompt_text, params=params)
                
                if not generated_response:
                    raise ValueError("Received empty text response from watsonx.ai")

                return {
                    "status": "success",
                    "is_reliable": True,
                    "granite_called": True,
                    "model_id": self.model_id,
                    "is_live_service": True,
                    "response_text": generated_response.strip(),
                    "category": prompt_package.get("category"),
                    "confidence_score": prompt_package.get("confidence_score")
                }
            except Exception as err:
                print(f"[ERROR] IBM Granite live API call failed: {err}")
                return {
                    "status": "api_error",
                    "is_reliable": False,
                    "granite_called": True,
                    "model_id": self.model_id,
                    "is_live_service": True,
                    "response_text": f"Error communicating with IBM Granite API: {str(err)}",
                    "explanation": "API request failed; falling back safely."
                }

        # 3. Safe Mock / Simulation Mode (When live credentials are not present)
        return self._generate_mock_granite_response(prompt_package)

    def _generate_mock_granite_response(self, prompt_package: Dict[str, Any]) -> Dict[str, Any]:
        """
        Simulates an IBM Granite response grounded strictly in retrieved facts.
        Used for local testing when live IBM API keys are not provided.
        """
        category_name = prompt_package.get("display_name", prompt_package.get("category", "Item"))
        facts = prompt_package.get("retrieved_facts", {}).get("guidance", {})
        metadata = prompt_package.get("retrieved_facts", {}).get("verification_metadata", {})

        do_s = facts.get("do_s", ["Follow local recycling practices."])
        dont_s = facts.get("dont_s", ["Do not contaminate recycling bins."])
        prep = facts.get("preparation_steps", ["Clean before binning."])
        impact = facts.get("environmental_impact_note", "Recycling helps protect our ecosystems.")
        source = metadata.get("source_name", "Verified Waste Guidelines")

        mock_text = (
            f"Here is your responsible disposal guidance for {category_name}:\n\n"
            f"1. Recommended Action: {do_s[0]}\n"
            f"2. Preparation: {prep[0]} Note: {dont_s[0]}\n"
            f"3. Environmental Impact: {impact}\n\n"
            f"(Source: {source}. Note: Local municipal rules may vary.)"
        )

        return {
            "status": "success",
            "is_reliable": True,
            "granite_called": True,
            "model_id": self.model_id,
            "is_live_service": False,
            "response_text": mock_text,
            "category": prompt_package.get("category"),
            "confidence_score": prompt_package.get("confidence_score"),
            "note": "Generated in safe test/mock mode because live IBM credentials were not provided."
        }


def generate_waste_guidance(
    predicted_category: str,
    confidence_score: float,
    threshold: Optional[float] = None
) -> Dict[str, Any]:
    """
    High-level convenience function connecting prompt_builder and Granite client.
    """
    prompt_package = build_rag_prompt(predicted_category, confidence_score, threshold=threshold)
    client = IBMGraniteClient()
    return client.generate_response(prompt_package)
